name: "delivery"
description: "RPM and DEB packages delivery"
inputs:
  distrib:
    description: "The distribution used for packaging"
    required: true
  cache_key:
    description: "The cached package key"
    required: true
  artifactory_token:
    description: "The token for artifactory"
    required: true
  stability:
    description: "branch stability (stable, testing, unstable, canary)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build name for RPM
      shell: bash
      if: ${{ startsWith(inputs.distrib, 'el') }}
      run: |
        echo "extfile=rpm" >> $GITHUB_ENV

    - name: Build name for DEB
      shell: bash
      if: ${{ inputs.distrib == 'bullseye' }}
      run: |
        echo "extfile=deb" >> $GITHUB_ENV

    - name: Use cache files
      uses: actions/cache@v3
      with:
        path: ./*.${{ env.extfile }}
        key: ${{ inputs.cache_key }}

    - uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://centreon.jfrog.io
        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}

    - name: Deliver packages to artifactory
      run: |
        if [[ "${{ env.extfile }}" == "rpm" ]] ; then
          jf rt upload "*.rpm" "rpm-connector-packs/${{ inputs.distrib }}/${{ inputs.stability }}/noarch/"
        elif [[ "${{ env.extfile }}" == "deb" ]] ; then
          jf rt upload "*.deb" "apt-connector-packs-${{ inputs.stability }}/pool/" --deb "${{ inputs.distrib }}/main/all"
        fi
      shell: bash
