ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye

RUN bash -e <<EOF

apt-get update
apt-get install -y git debmake pbuilder aptitude zstd ca-certificates luarocks lua5.4 liblua5.4-dev

ln -sf /usr/bin/lua5.4 /usr/bin/lua

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list

apt-get update
apt-get install -y nfpm=2.35.2

apt-get clean all

EOF
