ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:8

RUN <<EOF

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

dnf install -y rpm-build rpm-sign zstd nfpm lua
dnf clean all

EOF

WORKDIR /src
