name: "deb-delivery"
description: "Deliver deb packages"
inputs:
  module_name:
    description: "The package module name"
    required: true
  distrib:
    description: "The distribution used for packaging"
    required: true
  cache_key:
    description: "The cached package key"
    required: true
  stability:
    description: "The package stability (stable, testing, unstable)"
    required: true
  artifactory_token:
    description: "Artifactory token"
    required: true

runs:
  using: "composite"
  steps:
    - if: ${{ ! (inputs.distrib == 'jammy' && inputs.stability == 'stable') }}
      name: Use cache DEB files
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ./*.deb
        key: ${{ inputs.cache_key }}
        fail-on-cache-miss: true

    - if: ${{ ! (inputs.distrib == 'jammy' && inputs.stability == 'stable') }}
      uses: jfrog/setup-jfrog-cli@1641575d87647fb969c0545f0b6a76873e328b7c # v5.0.0
      env:
        JF_URL: https://centreon.jfrog.io
        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}

    - if: ${{ ! (inputs.distrib == 'jammy' && inputs.stability == 'stable') }}
      name: Publish DEBs
      env:
        MODULE_NAME: ${{ inputs.module_name }}
        DISTRIB: ${{ inputs.distrib }}
        STABILITY: ${{ inputs.stability }}
      run: |
        FILES="*.deb"

        if [[ "$DISTRIB" == "jammy" || "$DISTRIB" == "noble" ]]; then
          REPO_PREFIX="ubuntu"
        else
          REPO_PREFIX="apt"
        fi

        for FILE in $FILES; do
          echo "[DEBUG] - File: $FILE"

          ARCH=$(echo $FILE | cut -d '_' -f3 | cut -d '.' -f1)

          jf rt upload "$FILE" "${REPO_PREFIX}-plugins-$STABILITY/pool/$MODULE_NAME/" --deb "$DISTRIB/main/$ARCH"
        done
      shell: bash
