on:
  workflow_call:
    outputs:
      stability:
        description: "branch stability (stable, testing, unstable, canary)"
        value: ${{ jobs.get-environment.outputs.stability }}

jobs:
  get-environment:
    runs-on: ubuntu-22.04
    outputs:
      stability: ${{ steps.get_environment.outputs.stability }}

    steps:
      - uses: actions/checkout@v3

      - id: get_environment
        run: |
          case "$BRANCHNAME" in
            develop | dev-[2-9][0-9].[0-9][0-9].x)
              STABILITY="unstable"
              ;;
            release* | hotfix*)
              STABILITY="testing"
              ;;
            master | [2-9][0-9].[0-9][0-9].x)
              STABILITY="stable"
              ;;
            *)
              STABILITY="canary"
              ;;
          esac
          echo "stability=$STABILITY" >> $GITHUB_OUTPUT
        shell: bash
