name: stream-connectors-lib

# triggered by stream-connectors-ci.yml
# only builds and tests the library, its delivery is done by stream-connectors-lib-delivery.yml
# once the stream connectors have also been tested against it
on:
  workflow_call:

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml

  package:
    needs: [get-environment]

    strategy:
      fail-fast: false
      matrix:
        distrib: [el8, el9, el10, bookworm, trixie]
        include:
          - package_extension: rpm
            image: packaging-stream-connectors-nfpm-alma8
            distrib: el8
          - package_extension: rpm
            image: packaging-stream-connectors-nfpm-alma9
            distrib: el9
          - package_extension: rpm
            image: packaging-stream-connectors-nfpm-alma10
            distrib: el10
          - package_extension: deb
            image: packaging-stream-connectors-nfpm-bookworm
            distrib: bookworm
          - package_extension: deb
            image: packaging-stream-connectors-nfpm-trixie
            distrib: trixie

    runs-on: ubuntu-24.04

    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.image }}:latest
      credentials:
        username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
        password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}

    name: package ${{ matrix.distrib }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Package
        uses: ./.github/actions/package-nfpm
        with:
          nfpm_file_pattern: "packaging/connectors-lib/*.yaml"
          distrib: ${{ matrix.distrib }}
          version: "3.9.0" # previous version:"3.8.2"
          release: "1"
          package_extension: ${{ matrix.package_extension }}
          arch: all
          commit_hash: ${{ github.sha }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          rpm_gpg_key: ${{ secrets.RPM_GPG_SIGNING_KEY }}
          rpm_gpg_signing_key_id: ${{ secrets.RPM_GPG_SIGNING_KEY_ID }}
          rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
          stability: ${{ needs.get-environment.outputs.stability }}
          artifact_name: "package-stream-connectors-lib-${{ matrix.distrib }}"

  test-packages:
    needs: [get-environment, package]
    strategy:
      fail-fast: false
      matrix:
        include:
          - package_extension: rpm
            image: almalinux:8
            distrib: el8
          - package_extension: rpm
            image: almalinux:9
            distrib: el9
          - package_extension: rpm
            image: almalinux:10
            distrib: el10
          - package_extension: deb
            image: debian:bookworm
            distrib: bookworm
          - package_extension: deb
            image: debian:trixie
            distrib: trixie
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.image }}
    name: test packages on ${{ matrix.package_extension }} ${{ matrix.distrib }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Test packaged libs
        uses: ./.github/actions/test-packages
        with:
          package_extension: ${{ matrix.package_extension }}
          distrib: ${{ matrix.distrib }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          test_type: library

      - name: Upload error log
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: install_error_log_${{ matrix.distrib }}
          path: install_error_${{ matrix.distrib }}.log
